'use client';
import {useMemo,useState} from 'react';
const nav=['总览','关键词资产','广告活动','搜索词','优化工作台','新建广告方案','排名趋势','数据导入','数据源','规则设置','执行记录','系统设置'];
const kws=[
{k:'calf compression sleeves',asin:'B08BWRKH7R',org7:21,org14:37,ad7:5,ad14:11,sv:18600,c:3,o:14,cvr:13.5,acos:40.4,bid:.83,nbid:.74,a:'BID_DOWN'},
{k:'compression calf sleeves women',asin:'B08BWRWHZL',org7:34,org14:42,ad7:9,ad14:14,sv:8900,c:2,o:8,cvr:12.1,acos:46.9,bid:.71,nbid:.71,a:'KEEP'},
{k:'leg compression sleeves',asin:'B08BWRKH7R',org7:48,org14:64,ad7:12,ad14:21,sv:12100,c:4,o:7,cvr:10.9,acos:43.8,bid:.62,nbid:.70,a:'MOVE_TO_EXACT'},
{k:'calf sleeve',asin:'B08BWRWHZL',org7:73,org14:69,ad7:20,ad14:18,sv:6700,c:2,o:2,cvr:4.9,acos:121.2,bid:.79,nbid:.65,a:'BID_DOWN'}];
const camps=[
{name:'SP-3037-EXACT-CORE-202610',b:30,u:96,imp:28431,clk:412,ctr:1.45,cpc:.74,o:61,cvr:14.8,s:1036.39,acos:29.4,a:'SCALE'},
{name:'SP-3037-PHRASE-GROW-202610',b:20,u:73,imp:19820,clk:268,ctr:1.35,cpc:.68,o:29,cvr:10.8,s:492.71,acos:37.0,a:'KEEP'},
{name:'SP-3037-BROAD-DISCOVERY-202610',b:15,u:61,imp:17320,clk:211,ctr:1.22,cpc:.61,o:12,cvr:5.7,s:203.88,acos:63.1,a:'BID_DOWN'},
{name:'SP-3037-AUTO-DISCOVERY-202610',b:15,u:88,imp:22600,clk:301,ctr:1.33,cpc:.57,o:24,cvr:8.0,s:407.76,acos:42.1,a:'SEARCH_TERM_MINING'}];
const acts=[
['高','calf compression sleeves','SP-3037-EXACT-CORE-202610','BID_DOWN','USD 0.83','USD 0.74','ACOS高于目标，订单稳定，先降Bid控制CPC'],
['高','leg compression sleeves','SP-3037-BROAD-DISCOVERY-202610','MOVE_TO_EXACT','USD 0.62','USD 0.70','连续出单，迁移Exact并在Broad做Negative Exact'],
['中','compression calf sleeves women','SP-3037-PHRASE-GROW-202610','KEEP','USD 0.71','USD 0.71','转化稳定，继续积累数据']];
export default function Page(){
 const [p,setP]=useState('总览'),[d,setD]=useState(14),[q,setQ]=useState(''),[open,setOpen]=useState('');
 const data=useMemo(()=>kws.filter(x=>(x.k+' '+x.asin).toLowerCase().includes(q.toLowerCase())),[q]);
 return <div className="app"><aside className="side"><div className="brand">Amazon PPC Intelligence</div><div className="nav">{nav.map(n=><button key={n} className={p===n?'active':''} onClick={()=>setP(n)}>{n}</button>)}</div></aside><main className="main"><div className="top"><div><b>{p}</b><div className="small">Amazon US · 最近{d}天</div></div><div className="row"><span className="badge">DEMO 数据</span><span className="status">领星：待固定IP网关</span><span className="status">SIF：未配置</span><div className="tabs">{[7,14,30].map(x=><button key={x} className={d===x?'active':''} onClick={()=>setD(x)}>{x}天</button>)}</div></div></div><div className="content">
 {p==='总览'&&<><div className="notice">当前为功能验证数据。正式模式只使用领星/SIF真实同步或真实报表导入的数据。</div><div className="grid">{[['广告销售额','USD 2,140.91','↑ 12.4%'],['广告花费','USD 748.20','↑ 4.1%'],['ACOS','34.95%','目标 20%'],['TACOS','8.6%','目标 8%'],['订单','126','广告归因'],['CVR','10.9%','点击→订单'],['CPC','USD 0.66','平均'],['自然销售占比','58.3%','业务报告']].map(x=><div className="card metric" key={x[0]}><div className="label">{x[0]}</div><div className="value">{x[1]}</div><div className="sub">{x[2]}</div></div>)}</div><div className="section"><h3>今日优先处理</h3><div className="tablewrap"><table><thead><tr><th>优先级</th><th>关键词</th><th>动作</th><th>原因</th></tr></thead><tbody>{acts.map((a,i)=><tr key={i}><td>{a[0]}</td><td>{a[1]}</td><td className="mono">{a[3]}</td><td>{a[6]}</td></tr>)}</tbody></table></div></div></>}
 {p==='关键词资产'&&<div className="section"><h3>关键词资产中心</h3><div className="toolbar"><input className="input" placeholder="搜索关键词 / ASIN" value={q} onChange={e=>setQ(e.target.value)}/><button className="btn secondary">导出</button></div><div className="tablewrap"><table><thead><tr><th>关键词</th><th>ASIN</th><th>自然排名7/14</th><th>广告排名7/14</th><th>搜索量</th><th>活动数</th><th>订单</th><th>CVR</th><th>ACOS</th><th>Bid</th><th>建议</th></tr></thead><tbody>{data.map(x=><>{<tr key={x.k} onClick={()=>setOpen(open===x.k?'':x.k)} style={{cursor:'pointer'}}><td><b>{x.k}</b></td><td>{x.asin}</td><td>#{x.org7} / #{x.org14}</td><td>#{x.ad7} / #{x.ad14}</td><td>{x.sv.toLocaleString()}</td><td>{x.c}</td><td>{x.o}</td><td>{x.cvr}%</td><td className={x.acos>50?'bad':'warn'}>{x.acos}%</td><td>USD {x.bid.toFixed(2)}</td><td className="mono">{x.a}</td></tr>}{open===x.k&&<tr><td colSpan={11}><div className="detail"><div className="kv"><div><b>SP-3037-EXACT-CORE</b><div className="small">Exact · Bid USD {x.bid.toFixed(2)} · Budget USD 30</div></div><div><b>SP-3037-PHRASE-GROW</b><div className="small">Phrase · Bid USD 0.68 · Budget USD 20</div></div><div><b>建议Bid</b><div>USD {x.nbid.toFixed(2)}</div></div><div><b>证据</b><div className="small">排名趋势 + CVR + ACOS + 活动重叠</div></div></div></div></td></tr>}</>)}</tbody></table></div></div>}
 {p==='广告活动'&&<div className="section"><h3>广告活动诊断</h3><div className="tablewrap"><table><thead><tr><th>Campaign</th><th>预算</th><th>预算利用率</th><th>曝光</th><th>点击</th><th>CTR</th><th>CPC</th><th>订单</th><th>CVR</th><th>销售额</th><th>ACOS</th><th>动作</th></tr></thead><tbody>{camps.map(c=><tr key={c.name}><td><b>{c.name}</b></td><td>USD {c.b}</td><td>{c.u}%</td><td>{c.imp.toLocaleString()}</td><td>{c.clk}</td><td>{c.ctr}%</td><td>USD {c.cpc}</td><td>{c.o}</td><td>{c.cvr}%</td><td>USD {c.s}</td><td>{c.acos}%</td><td className="mono">{c.a}</td></tr>)}</tbody></table></div></div>}
 {p==='优化工作台'&&<div className="section"><h3>可执行优化动作</h3><div className="tablewrap"><table><thead><tr><th>优先级</th><th>关键词</th><th>Campaign</th><th>动作</th><th>当前Bid</th><th>调整后</th><th>证据</th></tr></thead><tbody>{acts.map((a,i)=><tr key={i}>{a.map((v,j)=><td key={j} className={j===3?'mono':''}>{v}</td>)}</tr>)}</tbody></table></div></div>}
 {p==='新建广告方案'&&<div className="section"><h3>新广告活动生成器</h3><div className="formgrid"><div><label>ASIN</label><select className="select"><option>B08BWRKH7R</option><option>B08BWRWHZL</option></select></div><div><label>策略</label><select className="select"><option>恢复自然排名</option><option>盈利放量</option><option>新品探索</option></select></div></div><div className="toolbar"><button className="btn">生成方案</button></div><div className="tablewrap"><table><thead><tr><th>Campaign</th><th>Targeting</th><th>预算</th><th>竞价策略</th><th>Placement</th><th>用途</th></tr></thead><tbody><tr><td>SP-B08BWRKH7R-EXACT-CORE-202610</td><td>Manual / Exact</td><td>USD 30/day</td><td>动态竞价-仅降低</td><td>TOS +40%</td><td>核心词</td></tr><tr><td>SP-B08BWRKH7R-PHRASE-GROW-202610</td><td>Manual / Phrase</td><td>USD 20/day</td><td>动态竞价-仅降低</td><td>TOS +20%</td><td>成长词</td></tr><tr><td>SP-B08BWRKH7R-AUTO-DISCOVERY-202610</td><td>Auto</td><td>USD 15/day</td><td>动态竞价-仅降低</td><td>0%</td><td>探索词</td></tr></tbody></table></div></div>}
 {p==='数据源'&&<div className="section"><h3>数据源</h3><div className="formgrid"><div className="card"><b>领星 OpenAPI</b><p className="small">https://openapi.lingxing.com</p><p className="warn">等待固定IP网关</p><button className="btn secondary">测试连接</button></div><div className="card"><b>SIF</b><p className="small">API / MCP Adapter</p><p className="warn">未配置</p><button className="btn secondary">配置</button></div></div></div>}
 {p==='数据导入'&&<div className="section"><h3>CSV / XLSX 数据导入</h3><div className="empty">支持 Campaign / Search Term / Advertised Product / Business Report / SIF关键词报告<br/><br/><button className="btn">选择文件</button><p className="small">导入后先字段映射和校验，再进入正式分析。</p></div></div>}
 {p==='规则设置'&&<div className="section"><h3>优化规则</h3><div className="formgrid">{[['目标ACOS','20'],['保本ACOS','28'],['TACOS目标','8'],['高点击无单阈值','18'],['最低CVR','8'],['预算利用率阈值','85'],['最大Bid调整幅度','20'],['自然排名保护阈值','20'],['放量最低订单','4']].map(x=><div key={x[0]}><label>{x[0]}</label><input className="input" defaultValue={x[1]}/></div>)}</div><div className="toolbar"><button className="btn">保存规则</button></div></div>}
 {['搜索词','排名趋势','执行记录','系统设置'].includes(p)&&<div className="section"><h3>{p}</h3><div className="empty">真实数据接通后自动启用。</div></div>}
 <div className="footer">Amazon PPC Intelligence · DEMO 与真实数据严格隔离</div></div></main></div>
}